steps:
  # 1. Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/hubfootball-repo/hubfootball:latest', '.']

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/hubfootball-repo/hubfootball:latest']

  # 3. Deploy to Cloud Run (例: サーバーレスで運用)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'hubfootball',
        '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/hubfootball-repo/hubfootball:latest',
        '--region', 'asia-northeast1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]